# Generated by Django 2.2.6 on 2019-10-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
