# Generated by Django 2.2.6 on 2019-10-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20191014_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
