# Generated by Django 2.2.6 on 2019-10-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speech',
            old_name='tittle',
            new_name='title',
        ),
    ]
