name: build

on:
  push:
    branches:
    - add-pipeline

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        echo hello world.