name: build

on:
  push:
    branches:
    - staging

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - run: |
        cd backend
        docker build -t preacher .